### ISSUE TITLE
compiler trashes entire root document

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#19]
In a wide range of situations (perhaps all), when the browser-based compiler encounters a syntax error, it trashes the entire HTML root document.  It shouldn't do that.  It shouldn't be reading or writing *any part* of the HTML document;   it should be a purely mathematical function of its explicit arguments, with no side-effects whatsoever.

More specifically, the compiler is observed to overwrite the HTML root document, both the HEAD and the BODY, placing an error message in the new BODY.  After destroying the document, the compiler terminates by throwing an exception, in which the 'message' field is a less-detailed description of the problem, omitting the source line number.  This is the observed behavior in the chrome environment;  firefox has additional problems on top of all this, as discussed in items #20 and #21.

As a workaround, I cobbled up a mechanism for saving a backup copy of the entire HTML document, and then restoring it.  This is an incomplete and stunningly inefficient workaround, but it is better than nothing.

* Suggestion:  The compiler should never ever read or write *any part* of the HTML document.  It should be a purely mathematical function of its explicit arguments, with no side-effects whatsoever.

* Suggestion:   The compiler should return a tuple consisting of the compiled code along with a list of warnings and error messages.  Rationale:
  * The exception-throwing mechanism is completely unsuitable for non-fatal warnings.
  * The exception-throwing mechanism is somewhat inconvenient even for fatal errors, especially considering that a better mechanism is needed for handling warnings anyway.

**Comment by BruceSherwood** [comment]
This is an artifact of the experiments you're performing of trying to use the compiler in a particular way. None of these terrible things happen in the glowscript.org environment nor the Trinket environment. I have no idea what the problem is, but the initial attempt you showed me, hello-gs-compile.html, has an unusual structure compared to the two prior uses of the GlowScript compiler, and it may well be possible that in further work you'll find a structure that works.
