### ISSUE TITLE
missing file lib/jquery/2.2dev/jquery.mousewheel.js

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#57]
git pull from https://github.com/BruceSherwood/glowscript results in a non-working setup
due to a missing file.

It's probably been broken since at least 3ff1b5ed (2016-02-24 22:25:04 -0700)

Suggestion:  
  git add lib/jquery/2.2dev/jquery.mousewheel.js

**Comment by BruceSherwood** [comment]
There is no folder lib/jquery/2.2dev. It is true that build.py mentions 2.2dev, a special version number for development testing purposes, but when build.py is used this value is changed to the appropriate release (currently 2.1). See docs/MakingNewVersion.txt. Note that if you specify "GlowScript 2.2dev VPython" it is the case that untrusted/run.js loads individual files instead of the minified libraries in packages. However, you say you get a "non-working setup", so evidently there is some problem I'm not aware of. What do you do that is "non-working"?

**Comment by JohnDenker** [comment]
> What do you do that is "non-working"?

:; git clone https://github.com/BruceSherwood/glowscript
:; cd glowscript/
:; python ./build.py 
Traceback (most recent call last):
  File "./build.py", line 111, in <module>
    minify( glowscript_libraries["run"], [], "package/glow." + version + ".min.js" )
  File "./build.py", line 90, in minify
    all = combine(inlibs)
  File "./build.py", line 86, in combine
    all.append( open(fn, "rt").read() )
IOError: [Errno 2] No such file or directory: 'lib/jquery/2.2dev/jquery.mousewheel.js'

This is 100% reproducible chez moi.

> There is no folder lib/jquery/2.2dev

Yes, that's the issue that I'm reporting, namely that it doesn't exist, even though build.py calls for it.

============

Further note that the list of files in build.py is inconsistent with the list of files in run.js (in the current repo).

If you're interested, I have code to fix this *permanently*, so that build.py reads run.js to automagicallly construct a consistent list.

**Comment by BruceSherwood** [comment]
Ah, understood. I think what you want to use is probably the new file
build_cli.py that a guy recently contributed. Take a look.

**Comment by BruceSherwood** [comment]
I've updated build.py and renamed it build_original.py.
