### ISSUE TITLE
build_original.py still has problems

### ISSUE THREAD

**Issue by JohnDenker** [BruceSherwood/glowscript#58]
*) Consider the recipe in the attached file:
[bug.log.txt](https://github.com/BruceSherwood/glowscript/files/351619/bug.log.txt)

This failure is 100% reproducible chez moi.

That means the recent "update" to build_original.py as stated in issue #57 does not solve the fundamental problem.  The "update" leaves the program inconsistent with property.js and inconsistent with the instructions.

*) The documentation now says build_cli.py is "more sophisticated" which indeed it is.  However, the documentation does not explain its relationship to build_original.py, and does not tell the user how to proceed.

====================

Suggestion:   It would be helpful to standardize on either build_original.py *OR* build_cli.py ... and then clarify the documentation accordingly.

*)  That way users know what to use.
*)  That way developers know where to focus their efforts.
 --  There's not much point in making "updates" to either one of those programs if the other is the only one that has a future.
 --  On the other side of the same coin, there's not much point in filing bug reports against either one of those programs if the other is the only one that has a future.

**Comment by BruceSherwood** [comment]
I made a mistake; I set version to 2.1 in build_original.py but forgot to set it to 2.1 in property.js. Now fixed in the repository. (I only set the version number to 2.2dev when doing certain kinds of testing.)

The fundamental issue is that the (complex) instructions in MakingNewVersion.txt, when used with the original build program, were adequate for me to keep going in the development, focusing on features that affect nearly 10000 glowscript.org users, not on build procedures that affect few people. It is only rather recently that multiple people have found it useful to use the GlowScript libraries in ways that have nothing to do with the particulars of glowscript.org, and which also are starting to affect sizable numbers of users: trinket.io, John Coady's initiation of what is now Jupyter VPython, recent interesting work by a guy in Finland, etc. That they were able to figure out how to make use of the libraries without good documentation on how to do so meant that I felt justified in keeping focused on making glowscript.org work well. I will now try to provide real documentation on how to use the libraries outside the glowscript.org environment.

**Comment by JohnDenker** [comment]
I still think it is not good practice to mention the **version** in the path to jquery.mousewheel.js on line 36 of build_original.py.  It makes the code almost impossible to use without making mistakes.

It would be better to avoid having paths baked into this code at all.   Note that build_cli.py avoids this problem by parsing run.js ... which is something that has been on the TODO list in build.py since forever.

Why not just document build_cli as the sole recommended solution, and stop worrying about build_original?

Having two such things is a recipe for wasted effort.

**Comment by BruceSherwood** [comment]
Okay, just ignore the existence of build_original.py. It will remain in existence until and unless the build instructions in MakingNewVersion.txt get thoroughly revised.
